spring.application.name=institution_gestion_notes
spring.datasource.url=jdbc:mysql://localhost:3306/institution_gestion_notes?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=49358485

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Security: default login page will be used (form login)
server.port=0

#server.error.include-message=always
#server.error.include-binding-errors=always

#server.error.include-stacktrace=always

# logs plus verbeux pour Spring (optionnel temporaire)
#logging.level.org.springframework=DEBUG*/

#logging.level.org.springframework=DEBUG
#logging.level.institution_gestion_notes=DEBUG